# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Hello sample
  displayName: Say Hello 
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: echo "Hello Azure DevOps"

- job: Gradle show tasks
  displayName: Show Gradle Tasks  
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: 
    - task: Gradle@2
      gradleWrapperFile: 'gradlew'
      tasks: 'tasks'

- job: Gradle build
  displayName: Gradle Build
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'